import { Database, emptyCard, Card } from "./domain";
import { scoreCard } from "./scoring";

export function seedDatabase(): Database {
  const businesses = [{ id: "b1", name: "Мастерская «Дело»" }, { id: "b2", name: "Маркет «Полка»" }, { id: "b3", name: "Школа «Орбита»" }, { id: "b4", name: "Логистика «Маршрут»" }, { id: "b5", name: "Фонд «Рядом»" }];
  const cards: Card[] = [
    { ...emptyCard(), title: "Заявки мастерской в одном месте", industry: "Услуги", problem: "Нужна система для учёта заявок клиентов нашей мастерской." },
    { ...emptyCard(), title: "Как сократить списания продуктов", industry: "Ритейл", context: "Остатки магазина ведём в таблицах вручную.", problem: "Не успеваем продавать продукты до истечения срока годности.", materials: "Выгрузка продаж и списаний за три месяца.", access: "Обезличенный CSV предоставит менеджер магазина.", users: "Управляющий и сотрудники магазина", result: "Панель с остатками и прогнозом списаний" },
    { ...emptyCard(), title: "Помощник для самостоятельной подготовки", industry: "Образование", context: "Преподаватели выдают задания через общий чат.", problem: "Студентам сложно находить задания по темам.", materials: "Есть 40 авторских упражнений и методические материалы.", access: "Учебный отдел передаст архив после первого созвона.", users: "Студенты первого курса", result: "Прототип каталога упражнений с поиском", success: "На демонстрации студент находит упражнение и сохраняет ответ.", constraints: "Без персональных данных учащихся" },
    { ...emptyCard(), title: "Планирование маршрутов доставки", industry: "Логистика", context: "Диспетчер каждый день вручную распределяет доставки.", problem: "Маршруты пересекаются, растёт время доставки.", materials: "Синтетический набор из 100 адресов и временных окон.", access: "CSV-файл выдаёт диспетчер при старте проекта.", users: "Диспетчеры службы доставки", result: "Прототип карты маршрутов и отчёт сравнения", success: "Тест на 100 адресах: все доставки распределены, окна соблюдены.", constraints: "Прототип за 4 недели, только синтетические адреса.", contact: "dispatch@example.com", feedback: "Еженедельный созвон с диспетчером, ответы в течение двух дней." },
    { ...emptyCard(), title: "Карта доступной помощи в районе", industry: "Социальные проекты", context: "Информация о помощи находится в разных чатах.", problem: "Жителям трудно найти подходящую инициативу рядом.", users: "Жители района и координаторы фонда", result: "Интерактивная карта инициатив", contact: "hello@example.org", feedback: "Координатор проводит консультацию раз в неделю." },
  ];
  const teams = [
    { id: "team1", name: "Код будущего", interests: "Сервисы для бизнеса", skills: "Интерфейсы, API, UX", technologies: "React, TypeScript, Node.js" },
    { id: "team2", name: "Data Nomads", interests: "Аналитика и ритейл", skills: "Анализ данных, визуализация", technologies: "Python, pandas, SQL" },
    { id: "team3", name: "Орбита Lab", interests: "Образовательные продукты", skills: "Исследования, дизайн, frontend", technologies: "Figma, React" },
    { id: "team4", name: "Маршрут 42", interests: "Логистика", skills: "Алгоритмы, карты, backend", technologies: "Python, FastAPI, Leaflet" },
    { id: "team5", name: "Вместе", interests: "Социальные проекты", skills: "UX, доступность, веб-разработка", technologies: "TypeScript, Next.js" },
  ];
  return { version: 1, businesses, teams, tasks: cards.map((card, i) => ({ id: `task${i + 1}`, businessId: businesses[i].id, description: card.problem, draft: { ...card }, confirmed: { ...card }, score: scoreCard(card).total, previousScore: scoreCard(card).total, revision: 1, published: true, createdAt: `2026-09-${String(10 + i).padStart(2, "0")}T10:00:00.000Z`, confirmedAt: "2026-09-15T10:00:00.000Z" })), proposals: teams.map((team, i) => ({ id: `proposal${i + 1}`, taskId: i === 1 ? "task1" : `task${i + 1}`, teamId: team.id, idea: ["Соберём удобный реестр заявок с поиском и статусами.", "Начнём с анализа процесса мастерской и прототипа панели.", "Сделаем каталог заданий с фильтрами по темам.", "Сравним алгоритмы маршрутизации на тестовых данных.", "Нарисуем доступную карту и проверим её с координатором."][i], plan: "Уточним задачу на встрече, подготовим прототип, проведём тест и передадим документацию.", timeframe: "Прототип через 3 недели", url: `https://example.com/demo/team-${i + 1}`, status: "pending", createdAt: "2026-09-16T10:00:00.000Z", requestId: `seed-${i}` })), milestones: [] };
}
