import { test, expect } from "@playwright/test";
test("Полный сценарий бизнеса и команды, прогресс, перезагрузка и низкий рейтинг", async ({ page, request }) => {
  const pageErrors: string[] = [];
  page.on("pageerror", error => pageErrors.push(error.message));
  const forbidden = await request.post("/api/command", { headers: { "x-demo-role": "business", "x-demo-id": "b1", origin: "https://example.com" }, data: { action: "reset", confirmation: "СБРОСИТЬ" } });
  expect(forbidden.status()).toBe(403);
  const reset = await request.post("/api/command", { headers: { "x-demo-role": "business", "x-demo-id": "b1", origin: "http://127.0.0.1:3100" }, data: { action: "reset", confirmation: "СБРОСИТЬ" } });
  expect(reset.ok()).toBe(true);
  await page.goto("/"); await expect(page.getByRole("heading", { name: /Большие идеи/ })).toBeVisible();
  await page.screenshot({ path: "test-results/desktop-dashboard.png", fullPage: true });
  await page.getByRole("button", { name: "Создать задачу", exact: true }).last().click();
  await page.getByLabel("Описание проблемы").fill("Нужна система для учёта заявок клиентов нашей мастерской.");
  await page.getByRole("button", { name: "Продолжить", exact: true }).click();
  await page.getByRole("button", { name: "Проанализировать описание" }).click();
  await expect(page.getByText("Резервный анализ: без внешней модели", { exact: true })).toBeVisible();
  const answers = ["Сейчас администратор записывает заявки в бумажный журнал.", "Администратор мастерской и пять мастеров", "Обезличенные примеры 30 заявок в CSV", "Владелец передаст CSV после первого созвона", "Веб-прототип реестра заявок с поиском и статусами", "Проверка: создать заявку, назначить мастера, найти и закрыть её", "Прототип за 3 недели, без персональных данных"];
  for (let i = 0; i < answers.length; i++) await page.locator(".question textarea").nth(i).fill(answers[i]);
  await page.getByRole("button", { name: "Сформировать карточку" }).click();
  await page.getByLabel("Название *", { exact: true }).fill("Демо: реестр заявок мастерской");
  await page.getByLabel("Отрасль / тема", { exact: true }).fill("Услуги");
  await page.getByLabel("Контакт бизнеса", { exact: true }).fill("workshop@example.com");
  await page.getByLabel("Взаимодействие и обратная связь", { exact: true }).fill("Созвон по вторникам и ответы в рабочем чате");
  await expect(page.locator(".score-ring strong")).toHaveText("100");
  await page.getByLabel("Контакт бизнеса", { exact: true }).fill(""); await expect(page.locator(".score-ring strong")).toHaveText("95");
  await page.getByLabel("Контакт бизнеса", { exact: true }).fill("workshop@example.com");
  await page.getByRole("button", { name: "Сохранить и подтвердить изменения" }).click();
  await expect(page.getByRole("button", { name: "Опубликовать задачу" })).toBeEnabled();
  await page.getByRole("button", { name: "Опубликовать задачу" }).click();
  await page.getByLabel("Демо-роль").selectOption("student");
  await page.getByLabel("Поиск задач").fill("Демо: реестр");
  await page.getByRole("button", { name: "Демо: реестр заявок мастерской" }).click();
  await page.getByLabel("Идея решения", { exact: true }).fill("Сделаем реестр с поиском и фильтрами статусов");
  await page.getByLabel("План", { exact: true }).fill("Интервью, прототип, проверка сценариев");
  await page.getByLabel("Предполагаемый срок", { exact: true }).fill("Три недели");
  await page.getByRole("button", { name: "Отправить отклик", exact: true }).click();
  await expect(page.getByText(/Отклик сохранён/)).toBeVisible();
  await page.getByRole("button", { name: /Мои отклики/ }).click();
  await expect(page.getByText("Сделаем реестр с поиском и фильтрами статусов", { exact: true })).toBeVisible();
  await page.reload(); await page.getByRole("button", { name: /Мои отклики/ }).click();
  await expect(page.getByText("Сделаем реестр с поиском и фильтрами статусов", { exact: true })).toBeVisible();
  await page.getByLabel("Демо-роль").selectOption("business"); await page.getByRole("button", { name: /Отклики команд/ }).click();
  const review = page.locator(".proposal").filter({ hasText: "Демо: реестр заявок мастерской" });
  await review.getByRole("button", { name: "Принять", exact: true }).click(); await expect(review.locator(".status")).toHaveText("Принят");
  await page.getByLabel("Демо-роль").selectOption("student"); await page.getByRole("button", { name: /Мои отклики/ }).click();
  const accepted = page.locator(".proposal").filter({ hasText: "Демо: реестр заявок мастерской" }); await expect(accepted.locator(".status")).toHaveText("Принят");
  await accepted.getByText("Отправить результат этапа", { exact: true }).click();
  await accepted.getByLabel("Что сделано").fill("Готов прототип с поиском заявок"); await accepted.getByLabel("Ссылка на результат").fill("https://example.com/result");
  await accepted.getByRole("button", { name: "Отправить результат", exact: true }).click();
  await expect(page.getByText("Результат отправлен на подтверждение бизнесу.")).toBeVisible();
  await page.getByLabel("Демо-роль").selectOption("business"); await page.getByRole("button", { name: /Отклики команд/ }).click();
  await page.getByRole("button", { name: "Подтвердить этап · +25" }).click();
  await expect(page.getByText("✓ Подтверждено · +25 баллов")).toBeVisible();
  await page.getByLabel("Демо-роль").selectOption("student"); await page.getByRole("button", { name: /Мои отклики/ }).click();
  await expect(page.getByText(/25 баллов за подтверждённые результаты/)).toBeVisible();
  await page.getByRole("button", { name: /Каталог задач/ }).click(); await page.getByLabel("Поиск задач").fill("");
  await page.getByLabel("Уровень готовности").selectOption("Черновик"); await page.getByRole("button", { name: "Заявки мастерской в одном месте" }).click();
  await expect(page.getByRole("button", { name: "Отправить отклик" })).toBeEnabled();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "Заявки мастерской в одном месте" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/mobile-detail.png", fullPage: true });
  expect(pageErrors).toEqual([]);
});
