"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Check, Sparkles, Save, Send } from "lucide-react";
import { Actor, AnalysisResult, Card, Command, Field, fields, fieldKeys, Task, ViewState } from "@/lib/domain";
import { scoreCard } from "@/lib/scoring";
import { ScoreBadge, ScorePanel } from "./score";

export type Run = (command: Command) => Promise<{ id: string; state: ViewState }>;
export function Builder({ task, actor, run, onPublished }: { task: Task; actor: Actor; run: Run; onPublished: () => void }) {
  const [step, setStep] = useState(task.confirmed ? 3 : 1);
  const [description, setDescription] = useState(task.description);
  const [card, setCard] = useState<Card>(task.draft);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [answers, setAnswers] = useState<Partial<Record<Field, string>>>({});
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const lock = useRef(false);
  useEffect(() => { if (step === 4) document.getElementById("confirmation")?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [step]);
  const dirty = JSON.stringify(card) !== JSON.stringify(task.confirmed);
  useEffect(() => { const leave = (e: BeforeUnloadEvent) => { if (JSON.stringify(card) !== JSON.stringify(task.draft) || description !== task.description) e.preventDefault(); }; window.addEventListener("beforeunload", leave); return () => window.removeEventListener("beforeunload", leave); }, [card, description, task]);
  async function action(fn: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); setMessage(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось выполнить действие"); } finally { lock.current = false; setBusy(false); } }
  async function analyze(operation: "analyze" | "structure") {
    await action(async () => {
      const response = await fetch("/api/ai", { method: "POST", headers: { "Content-Type": "application/json", "x-demo-role": actor.role, "x-demo-id": actor.id }, body: JSON.stringify({ description, operation, card, answers: Object.entries(answers).map(([field, value]) => ({ field, value })) }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error);
      setAnalysis(data); setCard(data.card); setStep(operation === "analyze" ? 2 : 3);
      await run({ action: "save", taskId: task.id, revision: task.revision, description, card: data.card, confirm: false });
    });
  }
  return <><div className="page-heading"><div><span className="eyebrow">КОНСТРУКТОР ЗАДАЧИ</span><h1>{task.confirmed ? "Уточните задачу. Усильте результат." : "От идеи — к понятной задаче"}</h1><p>AI помогает сформулировать. Вы проверяете факты и принимаете решения.</p></div><span className="pill">{task.published ? "Опубликована" : "Не опубликована"}</span></div><div className="steps">{["Описание", "Уточнение", "Карточка", "Подтверждение"].map((label, i) => <button key={label} aria-current={step === i + 1 ? "step" : undefined} className={step === i + 1 ? "current" : ""} onClick={() => setStep(i + 1)}><span>{step > i + 1 ? <Check size={14} /> : `0${i + 1}`}</span>{label}</button>)}</div>{error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice success" role="status">{message}</div>}{analysis && <div className="notice ai-notice"><Sparkles size={18} /><div><strong>{analysis.mode === "openai" ? "AI-анализ: OpenAI" : "Резервный анализ: без внешней модели"}</strong>{analysis.mode === "fallback" && <p>Внешняя модель недоступна или отключена. Данные сохранены; уточните поля вручную. В свободном тексте факты могут быть ещё не распределены по полям.</p>}</div></div>}<div className="builder-grid"><div>
      {step === 1 && <section className="panel form-panel"><span className="step-label">ШАГ 01</span><h2>С какой проблемой вы столкнулись?</h2><p>Расскажите своими словами: что происходит сейчас и что хотелось бы изменить.</p><label htmlFor="description">Исходное описание</label><textarea id="description" rows={7} value={description} maxLength={10000} onChange={e => setDescription(e.target.value)} placeholder="Нужна система для учёта заявок клиентов нашей мастерской." /><div className="between small muted"><span>Без выдуманных сроков, бюджета и обещаний</span><span>{description.length} / 10 000</span></div><div className="actions"><button className="primary" disabled={busy || description.trim().length < 5} onClick={() => analyze("analyze")}><Sparkles size={17} />{busy ? "Анализируем…" : "Проанализировать описание"}</button><button onClick={() => setStep(3)}>Заполнить вручную <ArrowRight size={16} /></button></div></section>}
      {step === 2 && <section className="panel form-panel"><span className="step-label">ШАГ 02</span><h2>Добавим ясности</h2><p>Ответьте на вопросы, которые помогут командам оценить задачу. Неизвестное можно оставить пустым.</p>{analysis ? <><div className="known"><b>Уже выделено:</b> {analysis.known.map(k => fields[k]).join(", ") || "Пока нет отдельных фактов"}<br /><b>Ещё не заполнено:</b> {analysis.missing.map(k => fields[k]).join(", ") || "Все поля заполнены"}</div>{analysis.questions.map((q, i) => <label className="question" key={q.id}><span className="question-number">{i + 1}</span><span>{q.text}<small>{fields[q.field]}</small><textarea rows={2} value={answers[q.field] ?? ""} onChange={e => setAnswers({ ...answers, [q.field]: e.target.value })} maxLength={1500} /></span></label>)}<button className="primary" disabled={busy} onClick={() => analyze("structure")}>{busy ? "Собираем карточку…" : "Сформировать карточку"}<ArrowRight size={17} /></button></> : <><p>Сначала проанализируйте описание или заполните карточку самостоятельно.</p><button onClick={() => setStep(1)}>К описанию</button></>}</section>}
      {step >= 3 && <section className="panel form-panel"><div className="between"><div><span className="step-label">ШАГ 03</span><h2>Карточка под вашим контролем</h2></div><span className="pill">Все поля редактируются</span></div><p>Проверьте факты перед подтверждением. Примеры в пустых полях не дают баллов.</p><div className="card-fields">{fieldKeys.map(key => <label key={key} className={key === "title" || key === "industry" ? "half" : ""}>{fields[key]}{key === "title" ? " *" : ""}{["title", "industry", "contact"].includes(key) ? <input value={card[key]} onChange={e => setCard({ ...card, [key]: e.target.value })} maxLength={key === "title" ? 200 : key === "industry" ? 120 : 500} placeholder="Не указано" /> : <textarea rows={2} value={card[key]} onChange={e => setCard({ ...card, [key]: e.target.value })} maxLength={1500} placeholder="Не указано — добавьте только известные факты" />}</label>)}</div><div id="confirmation" className="confirm-box"><span className="step-label">ШАГ 04 · ПОДТВЕРЖДЕНИЕ</span><h3>Сначала проверка, затем публикация</h3><p>Подтверждая, вы проверяете все сведения. Только эта версия карточки и рейтинга будет видна командам.</p><div className="actions"><button className="primary" disabled={busy || !card.title.trim()} onClick={() => action(async () => { await run({ action: "save", taskId: task.id, revision: task.revision, card, description, confirm: true }); setMessage("Изменения сохранены и подтверждены. Рейтинг обновлён."); })}><Check size={17} />Сохранить и подтвердить изменения</button><button disabled={busy} onClick={() => action(async () => { await run({ action: "save", taskId: task.id, revision: task.revision, card, description, confirm: false }); setMessage("Черновик сохранён. Подтверждённая версия не изменилась."); })}><Save size={16} />Сохранить черновик</button></div></div>{task.confirmed && <div className="published-box"><div><b>Подтверждённый рейтинг</b><ScoreBadge score={task.score} /><p>Изменение к предыдущему подтверждению: {task.score - task.previousScore > 0 ? "+" : ""}{task.score - task.previousScore}. {dirty ? "Есть неподтверждённые изменения." : "Все изменения подтверждены."}</p></div>{!task.published ? <button className="primary" disabled={busy || dirty} onClick={() => action(async () => { await run({ action: "publish", taskId: task.id, revision: task.revision }); onPublished(); })}><Send size={16} />Опубликовать задачу</button> : <span className="pill green">В публичном каталоге</span>}</div>}</section>}
    </div><aside><ScorePanel card={card} confirmedDelta={task.confirmed ? task.score - task.previousScore : undefined} /><div className="panel note"><b>Сейчас подтверждено: {task.score} / 100</b><p>Предварительное изменение: {scoreCard(card).total - task.score > 0 ? "+" : ""}{scoreCard(card).total - task.score}. Сохранение без подтверждения не меняет позицию в каталоге.</p></div></aside></div></>;
}
