"use client";
import { FormEvent, useRef, useState } from "react";
import { Check, ExternalLink, Send, X } from "lucide-react";
import { Actor, Proposal, proposalStatus, ViewState } from "@/lib/domain";
import { Run } from "./builder";

export function ProposalForm({ taskId, teamName, run }: { taskId: string; teamName: string; run: Run }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  const requestId = useRef<string | null>(null); const locked = useRef(false);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (locked.current) return; locked.current = true; setBusy(true); setError("");
    const form = e.currentTarget; const data = new FormData(form); requestId.current ??= crypto.randomUUID();
    try { await run({ action: "proposal", taskId, idea: String(data.get("idea")), plan: String(data.get("plan")), timeframe: String(data.get("timeframe")), url: String(data.get("url")), requestId: requestId.current }); setDone(true); requestId.current = null; form.reset(); }
    catch (e) { setError(e instanceof Error ? e.message : "Не удалось отправить отклик"); }
    finally { setBusy(false); locked.current = false; }
  }
  return <section className="panel form-panel"><span className="eyebrow">ВАШ СЛЕДУЮЩИЙ ПРОЕКТ</span><h2>Предложите решение</h2><p>Команда: <b>{teamName}</b>. Рейтинг задачи не ограничивает отклики.</p>{done && <div className="notice success" role="status">Отклик сохранён. Следите за решением в разделе «Мои отклики».</div>}{error && <div className="notice error" role="alert">{error}</div>}<form onSubmit={submit}><label>Идея решения<textarea name="idea" required minLength={5} maxLength={3000} rows={3} placeholder="Как вы предлагаете решить задачу?" /></label><label>План<textarea name="plan" required minLength={5} maxLength={3000} rows={3} placeholder="Основные шаги и результат каждого этапа" /></label><label>Предполагаемый срок<input name="timeframe" required minLength={5} maxLength={300} placeholder="Например: прототип за 3 недели" /></label><label>Ссылка на прототип / материалы <small>необязательно</small><input name="url" type="url" maxLength={1000} placeholder="https://example.com/prototype" /></label><button className="primary" disabled={busy}><Send size={16} />{busy ? "Отправляем…" : "Отправить отклик"}</button></form></section>;
}
function ProgressForm({ proposalId, run }: { proposalId: string; run: Run }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const locked = useRef(false); const requestId = useRef<string | null>(null);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (locked.current) return; locked.current = true; setBusy(true); const form = e.currentTarget; const data = new FormData(form); requestId.current ??= crypto.randomUUID(); try { await run({ action: "milestone", proposalId, description: String(data.get("description")), url: String(data.get("url")), requestId: requestId.current }); form.reset(); requestId.current = null; setMessage("Результат отправлен на подтверждение бизнесу."); } catch (e) { setMessage(e instanceof Error ? e.message : "Ошибка сохранения"); } finally { setBusy(false); locked.current = false; } }
  return <details className="progress-form"><summary>Отправить результат этапа</summary><p>25 баллов прогресса после подтверждения бизнесом.</p><form onSubmit={submit}><label>Что сделано<textarea name="description" required minLength={5} maxLength={3000} rows={2} /></label><label>Ссылка на результат<input name="url" type="url" required maxLength={1000} /></label><button disabled={busy}>Отправить результат</button>{message && <p role="status">{message}</p>}</form></details>;
}
export function ProposalList({ proposals, state, actor, run }: { proposals: Proposal[]; state: ViewState; actor: Actor; run: Run }) {
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const lock = useRef(false);
  async function decide(id: string, action: () => Promise<unknown>) { if (lock.current) return; lock.current = true; setBusy(id); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка сохранения"); } finally { setBusy(""); lock.current = false; } }
  if (!proposals.length) return <div className="panel empty"><Send size={32} /><h3>Откликов пока нет</h3><p>{actor.role === "business" ? "Опубликуйте задачу: команды смогут предложить решения." : "Выберите задачу в каталоге и предложите свой подход."}</p></div>;
  return <>{error && <div className="notice error" role="alert">{error}</div>}<div className="proposal-grid">{proposals.map(p => { const team = state.teams.find(t => t.id === p.teamId)!; const task = [...state.tasks, ...state.catalog].find(t => t.id === p.taskId); return <article className="panel proposal" key={p.id}><div className="between"><span className={`status ${p.status}`}>{proposalStatus[p.status]}</span><small className="muted">{new Date(p.createdAt).toLocaleDateString("ru-RU")}</small></div><h3>{team.name}</h3><p className="proposal-task">{task?.confirmed?.title ?? "Задача бизнеса"}</p><div className="team-skills"><div className="skill-chips">{team.skills.split(",").map(skill => <span key={skill}>{skill.trim()}</span>)}</div><div className="skill-chips technology-chips">{team.technologies.split(",").map(technology => <span key={technology}>{technology.trim()}</span>)}</div><small>Интересы: {team.interests}</small></div><dl><dt>Идея решения</dt><dd>{p.idea}</dd><dt>План</dt><dd>{p.plan}</dd><dt>Предполагаемый срок</dt><dd>{p.timeframe}</dd></dl>{p.url && <a className="text-link" href={p.url} target="_blank" rel="noreferrer">Прототип / материалы <ExternalLink size={14} /></a>}{actor.role === "business" && <div className="actions"><button className="primary" disabled={!!busy || p.status === "accepted"} onClick={() => decide(p.id, () => run({ action: "decision", proposalId: p.id, status: "accepted" }))}><Check size={16} />Принять</button><button disabled={!!busy || p.status === "rejected"} onClick={() => decide(p.id, () => run({ action: "decision", proposalId: p.id, status: "rejected" }))}><X size={16} />Отклонить</button>{p.status !== "pending" && <button className="link-button" disabled={!!busy} onClick={() => decide(p.id, () => run({ action: "decision", proposalId: p.id, status: "pending" }))}>Вернуть на рассмотрение</button>}</div>}{state.milestones.filter(m => m.proposalId === p.id).map(m => <div className="milestone" key={m.id}><b>{m.confirmedAt ? "✓ Подтверждено · +25 баллов" : "Результат ожидает подтверждения"}</b><p>{m.description}</p><a href={m.url} target="_blank" rel="noreferrer">Открыть результат ↗</a>{actor.role === "business" && !m.confirmedAt && p.status === "accepted" && <button disabled={!!busy} onClick={() => decide(m.id, () => run({ action: "confirmMilestone", milestoneId: m.id }))}>Подтвердить этап · +25</button>}</div>)}{actor.role === "student" && p.status === "accepted" && <ProgressForm proposalId={p.id} run={run} />}</article>; })}</div></>;
}
