"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, BriefcaseBusiness, CheckCheck, CircleHelp, GraduationCap, LayoutDashboard, ListFilter, Plus, Search, Sparkles, Target, RotateCcw, Inbox, Globe2, LoaderCircle } from "lucide-react";
import { Actor, Command, fieldKeys, fields, levels, PublicTask, Task, ViewState } from "@/lib/domain";
import { readinessLevel } from "@/lib/scoring";
import { Builder } from "./builder";
import { ScoreBadge, ScorePanel } from "./score";
import { ProposalForm, ProposalList } from "./proposals";

type Screen = "dashboard" | "catalog" | "new" | "builder" | "detail" | "proposals";
const initialActor: Actor = { role: "business", id: "b1" };
export function Workspace() {
  const [actor, setActor] = useState<Actor>(initialActor); const [state, setState] = useState<ViewState | null>(null);
  const [screen, setScreen] = useState<Screen>("dashboard"); const [selected, setSelected] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [reset, setReset] = useState(false);
  const [query, setQuery] = useState(""); const [industry, setIndustry] = useState(""); const [level, setLevel] = useState("");
  const generation = useRef(0); const createId = useRef<string | null>(null); const createLock = useRef(false);
  const refresh = useCallback(async (identity: Actor) => { const version = ++generation.current; const response = await fetch("/api/state", { headers: { "x-demo-role": identity.role, "x-demo-id": identity.id }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (version === generation.current) { setState(data); setError(""); } }, []);
  useEffect(() => { let identity = initialActor; try { const saved = JSON.parse(localStorage.getItem("ai-sana-actor") || "null"); if (saved && ["business", "student"].includes(saved.role) && typeof saved.id === "string") identity = saved; } catch {} Promise.resolve().then(() => { setActor(identity); if (identity.role === "student") setScreen("catalog"); return refresh(identity); }).catch(e => setError(e.message)); }, [refresh]);
  useEffect(() => { const focus = () => refresh(actor).catch(e => setError(e.message)); window.addEventListener("focus", focus); return () => window.removeEventListener("focus", focus); }, [actor, refresh]);
  async function run(command: Command) { const response = await fetch("/api/command", { method: "POST", headers: { "Content-Type": "application/json", "x-demo-role": actor.role, "x-demo-id": actor.id }, body: JSON.stringify(command) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setState(result.state); return result as { id: string; state: ViewState }; }
  function navigate(next: Screen, id = "") { setScreen(next); setSelected(id); setError(""); if (next !== "builder" && next !== "new") void refresh(actor).catch(e => setError(e.message)); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function switchActor(next: Actor) { setActor(next); setState(null); setSelected(""); setScreen(next.role === "business" ? "dashboard" : "catalog"); localStorage.setItem("ai-sana-actor", JSON.stringify(next)); try { await refresh(next); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка загрузки"); } }
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (createLock.current) return; createLock.current = true; setBusy(true); createId.current ??= crypto.randomUUID(); const description = String(new FormData(e.currentTarget).get("description")); try { const result = await run({ action: "create", description, requestId: createId.current }); createId.current = null; navigate("builder", result.id); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка сохранения"); } finally { setBusy(false); createLock.current = false; } }
  const business = state?.businesses.find(b => b.id === actor.id); const team = state?.teams.find(t => t.id === actor.id);
  const task = state?.tasks.find(t => t.id === selected); const detail = state?.catalog.find(t => t.id === selected);
  const catalog = state?.catalog.filter(t => { const card = t.confirmed!; return (!query || `${card.title} ${card.problem} ${card.context} ${card.result}`.toLowerCase().includes(query.toLowerCase())) && (!industry || card.industry === industry) && (!level || readinessLevel(t.score) === level); }) ?? [];
  function TaskCard({ task: t, own = false }: { task: PublicTask | Task; own?: boolean }) { const card = t.confirmed ?? ("draft" in t ? t.draft : null); if (!card) return null; return <article className={`panel task-card ${t.score >= 90 ? "priority" : ""}`}><div className="between"><span className="topic">{card.industry || "Тема не указана"}</span><span className="small muted">{own ? t.published ? "Опубликована" : "Не опубликована" : `№ ${t.id.slice(-4).toUpperCase()}`}</span></div><h3><button className="title-button" onClick={() => navigate(own ? "builder" : "detail", t.id)}>{card.title || "Новая задача"}<ArrowUpRight size={20} /></button></h3><p className="business-name">{state?.businesses.find(b => b.id === t.businessId)?.name}</p><p className="task-problem">{card.problem || "Потребность ещё не описана"}</p><div className="deliverable"><Target size={17} /><span>{card.result || "Ожидаемый результат пока не указан"}</span></div>{card.constraints && <p className="constraints">{card.constraints}</p>}<div className="task-footer"><ScoreBadge score={t.score} /><button className="link-button" onClick={() => navigate(own ? "proposals" : "detail", t.id)}><Inbox size={15} />{state?.proposalCounts[t.id] ?? 0} откликов</button></div></article>; }
  return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/" aria-label="AI Sana — главная"><span className="brand-symbol"><Sparkles size={23} /></span><span>AI Sana<span className="brand-dot">.</span></span></Link><div className="workspace-label">ПРОСТРАНСТВО ВОЗМОЖНОСТЕЙ</div><nav>{actor.role === "business" && <button className={screen === "dashboard" ? "active" : ""} onClick={() => navigate("dashboard")}><LayoutDashboard size={19} />Мои задачи</button>}<button className={screen === "catalog" || screen === "detail" ? "active" : ""} onClick={() => navigate("catalog")}><Globe2 size={19} />Каталог задач<span className="nav-count">{state?.catalog.length ?? "—"}</span></button><button className={screen === "proposals" ? "active" : ""} onClick={() => navigate("proposals")}><Inbox size={19} />{actor.role === "business" ? "Отклики команд" : "Мои отклики"}{!!state?.proposals.length && <span className="nav-count">{state.proposals.length}</span>}</button>{actor.role === "business" && <button className={screen === "new" || screen === "builder" ? "active" : ""} onClick={() => navigate("new")}><Plus size={19} />Создать задачу</button>}</nav><div className="sidebar-note"><span className="tiny-star">✧</span><h3>Ясная задача.<br />Сильное решение.</h3><p>Добавляйте детали, повышайте готовность и находите команды.</p><div className="mini-bars"><i /><i /><i /><i /><i /></div></div><div className="sidebar-bottom"><span className="online-dot" />Локальное демо · данные сохраняются<button onClick={() => setReset(true)} disabled={actor.role !== "business"}><RotateCcw size={14} />Сбросить демо-данные</button></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">Рабочее пространство <span>/</span> <b>{actor.role === "business" ? "Бизнес" : "Команда"}</b></div><div className="identity-controls"><span className="demo-label">DEMO · без авторизации</span><label className="sr-only" htmlFor="role">Демо-роль</label><select id="role" value={actor.role} onChange={e => void switchActor(e.target.value === "business" ? initialActor : { role: "student", id: "team1" })}><option value="business">Бизнес</option><option value="student">Студенческая команда</option></select><label className="sr-only" htmlFor="identity">Текущий профиль</label><select id="identity" value={actor.id} onChange={e => void switchActor({ ...actor, id: e.target.value })}>{(actor.role === "business" ? state?.businesses : state?.teams)?.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><span className="avatar">{actor.role === "business" ? <BriefcaseBusiness size={19} /> : <GraduationCap size={21} />}</span></div></header><main>{error && <div className="notice error" role="alert">{error}<button onClick={() => refresh(actor).catch(e => setError(e.message))}>Повторить загрузку</button></div>}{!state ? <div className="empty"><LoaderCircle className="spin" size={30} /><h2>Загружаем пространство…</h2></div> : <>
    {screen === "dashboard" && <><div className="page-heading"><div><span className="eyebrow">КАБИНЕТ БИЗНЕСА</span><h1>Большие идеи начинаются<br />с понятных задач<span className="accent">.</span></h1><p>{business?.name} · Превратите реальную потребность в студенческий проект.</p></div><button className="primary" onClick={() => navigate("new")}><Plus size={18} />Создать задачу</button></div><div className="stats-grid"><div className="panel stat"><span>Ваши задачи <BriefcaseBusiness size={18} /></span><strong>{state.tasks.length}</strong><small>{state.tasks.filter(t => t.published).length} в публичном каталоге</small></div><div className="panel stat"><span>Средняя готовность <Target size={18} /></span><strong>{state.tasks.length ? Math.round(state.tasks.reduce((s, t) => s + t.score, 0) / state.tasks.length) : 0}<em>/ 100</em></strong><small>По подтверждённым карточкам</small></div><div className="panel stat"><span>Отклики команд <Inbox size={18} /></span><strong>{state.proposals.length}</strong><small>{state.proposals.filter(p => p.status === "pending").length} ожидают вашего решения</small></div><div className="panel stat"><span>Принято команд <CheckCheck size={18} /></span><strong>{state.proposals.filter(p => p.status === "accepted").length}</strong><small>Выбор всегда за вами</small></div></div><section className="improve-banner"><div className="banner-icon"><Sparkles size={26} /></div><div><span className="eyebrow">БОЛЬШЕ ЯСНОСТИ — БОЛЬШЕ ВОЗМОЖНОСТЕЙ</span><h2>Помогите командам понять вашу задачу</h2><p>Уточните данные, результат и критерии успеха. Рейтинг готовности покажет, что ещё можно улучшить.</p></div><button onClick={() => state.tasks[0] ? navigate("builder", state.tasks[0].id) : navigate("new")}>Улучшить карточку <ArrowRight size={17} /></button></section><div className="section-heading"><h2>Мои задачи <span>{state.tasks.length}</span></h2><span className="muted small">Готовность и публикация — разные статусы</span></div><div className="task-grid">{state.tasks.map(t => <TaskCard key={t.id} task={t} own />)}<button className="new-task-card" onClick={() => navigate("new")}><span><Plus size={26} /></span><b>Есть ещё одна задача?</b><small>Опишите её — мы поможем с остальным</small></button></div></>}
    {screen === "new" && <><div className="page-heading"><div><span className="eyebrow">НОВАЯ ВОЗМОЖНОСТЬ</span><h1>Расскажите о своей задаче</h1><p>Начните с пары предложений. Детали уточним на следующем шаге.</p></div></div><form className="panel form-panel new-form" onSubmit={create}><label>Описание проблемы<textarea name="description" required minLength={5} maxLength={10000} rows={7} placeholder="Нужна система для учёта заявок клиентов нашей мастерской." /></label><div className="notice"><CircleHelp size={18} /><span>Задача сохранится как неопубликованный черновик. Публикация — только после вашего подтверждения.</span></div><button className="primary" disabled={busy}>{busy ? "Сохраняем…" : "Продолжить"}<ArrowRight size={17} /></button></form></>}
    {screen === "builder" && (task ? <Builder key={task.id} task={task} actor={actor} run={run} onPublished={() => navigate("catalog")} /> : <div className="empty">Задача не найдена</div>)}
    {screen === "catalog" && <><div className="page-heading"><div><span className="eyebrow">РЕАЛЬНЫЙ БИЗНЕС. РЕАЛЬНЫЙ ОПЫТ.</span><h1>Найдите задачу со смыслом<span className="accent">.</span></h1><p>Выбирайте интересный проект, предлагайте решение и создавайте результат вместе.</p></div><span className="catalog-mark"><Globe2 size={30} /></span></div><div className="catalog-summary"><span><span className="online-dot" />{state.catalog.length} открытых задач</span><span>Все команды могут откликнуться · без ограничений по рейтингу</span></div><div className="filters panel"><label className="search"><Search size={18} /><input aria-label="Поиск задач" placeholder="Поиск по названию или описанию" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Отрасль" value={industry} onChange={e => setIndustry(e.target.value)}><option value="">Все отрасли</option>{[...new Set(state.catalog.map(t => t.confirmed!.industry))].filter(Boolean).sort().map(i => <option key={i}>{i}</option>)}</select><select aria-label="Уровень готовности" value={level} onChange={e => setLevel(e.target.value)}><option value="">Любая готовность</option>{levels.map(l => <option key={l}>{l}</option>)}</select><button className="icon-button" aria-label="Сбросить фильтры" onClick={() => { setQuery(""); setIndustry(""); setLevel(""); }}><RotateCcw size={17} /></button></div><div className="section-heading"><h2>Открытые задачи <span>{catalog.length}</span></h2><span className="muted small"><ListFilter size={15} /> Сначала с высокой готовностью</span></div>{catalog.length ? <div className="task-grid">{catalog.map(t => <TaskCard key={t.id} task={t} />)}</div> : <div className="panel empty"><Search size={30} /><h3>Задачи не найдены</h3><p>Измените запрос или сбросьте фильтры.</p></div>}</>}
    {screen === "detail" && (detail?.confirmed ? <><button className="back-button" onClick={() => navigate("catalog")}><ArrowLeft size={16} />К каталогу</button><div className="page-heading"><div><span className="eyebrow">{detail.confirmed.industry || "ЗАДАЧА БИЗНЕСА"}</span><h1>{detail.confirmed.title}</h1><p>{state.businesses.find(b => b.id === detail.businessId)?.name} · {state.proposalCounts[detail.id]} откликов</p></div><ScoreBadge score={detail.score} /></div><div className="builder-grid"><div><section className="panel detail-card">{fieldKeys.filter(k => !["title", "industry"].includes(k)).map(k => <div key={k}><h3>{fields[k]}</h3><p>{detail.confirmed![k] || <span className="muted">Не указано</span>}</p></div>)}</section>{actor.role === "student" ? <ProposalForm taskId={detail.id} teamName={team?.name ?? ""} run={run} /> : <div className="notice"><GraduationCap size={20} />Переключитесь на студенческую команду, чтобы отправить отклик.</div>}</div><ScorePanel card={detail.confirmed} official={detail.score} previous={detail.previousScore} /></div></> : <div className="empty">Опубликованная задача не найдена.</div>)}
    {screen === "proposals" && <><div className="page-heading"><div><span className="eyebrow">{actor.role === "business" ? "ОТ ИДЕИ К СОТРУДНИЧЕСТВУ" : "ПРОЕКТЫ ВАШЕЙ КОМАНДЫ"}</span><h1>{actor.role === "business" ? "Отклики команд" : "Мои отклики"}</h1><p>{actor.role === "business" ? "Сравните подходы. Вы можете принять одну, несколько или ни одной команды." : `${team?.name} · ${state.teamPoints[actor.id] ?? 0} баллов за подтверждённые результаты`}</p></div><button onClick={() => refresh(actor).catch(e => setError(e.message))}><RotateCcw size={16} />Обновить</button></div>{actor.role === "business" && <label className="review-filter">Задача<select value={selected} onChange={e => setSelected(e.target.value)}><option value="">Все мои задачи</option>{state.tasks.map(t => <option key={t.id} value={t.id}>{t.confirmed?.title || t.draft.title || "Новая задача"}</option>)}</select></label>}<ProposalList proposals={state.proposals.filter(p => !selected || p.taskId === selected)} state={state} actor={actor} run={run} /></>}
    </>}<footer>AI Sana <span>Бизнес формулирует. Команды предлагают. Люди решают.</span><span>Хакатон · демо</span></footer></main></div>{reset && <div className="modal-backdrop"><section className="panel modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Сбросить демо-данные?</h2><p>Все добавленные задачи, отклики, решения и результаты будут удалены. Восстановятся 5 исходных задач, 5 команд и 5 откликов.</p><div className="actions"><button onClick={() => setReset(false)} disabled={busy}>Отмена</button><button className="danger" disabled={busy} onClick={async () => { setBusy(true); try { await run({ action: "reset", confirmation: "СБРОСИТЬ" }); setReset(false); navigate("dashboard"); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка сброса"); setReset(false); } finally { setBusy(false); } }}>Подтвердить сброс</button></div></section></div>}</div>;
}
